### ISSUE TITLE
Why the version 1.2.1 is not published yet?

### ISSUE THREAD

**Issue by dirceusemighini** [input-output-hk/scrypto#17]
I've tried to follow the README using the version 1.2.1 but sbt can't find it, I've tried to look into sonatype and also in mavenrepository but can't find it either. Why it hasn't been published yet?

**Comment by catena2w** [comment]
1.2.1 is published (http://mvnrepository.com/artifact/org.scorexfoundation/scrypto_2.12/1.2.1) while latest stable version is 1.3.3.

**Comment by dirceusemighini** [comment]
Nice
