### ISSUE TITLE
Write specification for AVL+ implementation

### ISSUE THREAD

**Issue by kushti** [input-output-hk/scrypto#70]
Scrypto has an implementation of AVL+ tree described in briefly in https://eprint.iacr.org/2016/994 , see BatchAVLProver/BatchAVLVerifier classes and further scorex.crypto.authds.avltree.batch package. 

In particular, this tree is tailored for blockchain applications. See the presentation from RWC2017 https://www.youtube.com/watch?v=PHY7JnLrK5o 

There's no detailed specification for the tree (construction, serialization) and proofs (algorithms, serialization) yet, but it is needed, as the tree is used in Ergo blockchain (core, contracts), and possibly , somewhere else.

**Comment by knizhnik** [comment]
https://github.com/knizhnik/scorex_crypto_avltree/blob/main/crypto_avltree.md

**Comment by stenolog** [comment]
This looks like done, or is more work needed?
