### ISSUE TITLE
JDK7 build does not work because BouncyCastle 1.66 dependency requires Java 16

### ISSUE THREAD

**Issue by MrStahlfelge** [input-output-hk/scrypto#81]
When using `org.scorexfoundation:scrypto_2.11:2.1.10` dependency, the build on Android fails:

`Reason: IllegalArgumentException, message: Unsupported class file major version 59`

It is needed to use org.bouncycastle:bcprov-jdk15to18:1.66 instead.

**Comment by aslesarenko** [comment]
@MrStahlfelge please create a PR with the necessary changes.

**Comment by MrStahlfelge** [comment]
Unfortunately, I cannot come up with an own PR because I am not familiar with the Scala Build Tools used here.

When fetching the lib with Gradle, I can workaround the problem with the following dependency declaration:

```
    implementation ('dependencyusingscrypto') {
                exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
            }
      implementation "org.bouncycastle:bcprov-jdk15to18:1.66"
```

This way everything works as expected.
